// Generated by scripts/pose/prepare-models.mjs from hash-pinned publisher artifacts.
// Provenance: docs/operations/2026-09-30-pose-model-distribution.md.
export interface PoseModelChunk { url: string; byteLength: number; sha256: string }
export interface PoseModelSpec { id: string; name: string; totalByteLength: number; sha256: string; chunks: readonly PoseModelChunk[] }
export const POSE_MODELS: readonly PoseModelSpec[] = [
  {
    "id": "detector",
    "name": "YOLOX-M",
    "totalByteLength": 101400344,
    "sha256": "3dea6513388889f0fff4b77bf7a26013600321b9eb9ceb0e9a400a82572f5f23",
    "chunks": [
      {
        "url": "/models/pose/3dea6513388889f0/0.bin",
        "byteLength": 25165824,
        "sha256": "a0567c9e5a018171c90b7ef758839dc0e9d6e7dadc77a41e135e3b42df4b5558"
      },
      {
        "url": "/models/pose/3dea6513388889f0/1.bin",
        "byteLength": 25165824,
        "sha256": "ac8ca14615fd6082d1b83f14c6a116109546dd3cc390a19998c45a3cfef3c7de"
      },
      {
        "url": "/models/pose/3dea6513388889f0/2.bin",
        "byteLength": 25165824,
        "sha256": "c4b8d94524eac479215c534812b583c9f183c111c9fd2f48bd9881d3ea57a13c"
      },
      {
        "url": "/models/pose/3dea6513388889f0/3.bin",
        "byteLength": 25165824,
        "sha256": "8cd1937e3e0ffb45a4729babfd9c4951e086a324d1d3ea2aa63c389eed1cf502"
      },
      {
        "url": "/models/pose/3dea6513388889f0/4.bin",
        "byteLength": 737048,
        "sha256": "621b346425f2b77c82e97606275d3d1f641129b7809df36fecd76c234a779148"
      }
    ]
  },
  {
    "id": "pose",
    "name": "RTMW-X",
    "totalByteLength": 228708578,
    "sha256": "9a9bc17c13ff0a1e37507f45a037a21bc410cd08374b0e664c57d0080843aa58",
    "chunks": [
      {
        "url": "/models/pose/9a9bc17c13ff0a1e/0.bin",
        "byteLength": 25165824,
        "sha256": "daffaffafd088ca4a0d4125d45af35983d940bd59aec710595b6dab0617e28df"
      },
      {
        "url": "/models/pose/9a9bc17c13ff0a1e/1.bin",
        "byteLength": 25165824,
        "sha256": "a157ce8e91ca2790c01d1c93a9a17511e2a8a439049cb5a62d2acc246ab087af"
      },
      {
        "url": "/models/pose/9a9bc17c13ff0a1e/2.bin",
        "byteLength": 25165824,
        "sha256": "c04991dbcd2a7383b99eeeec0b1a27d81479b7619991a91a547c284ad9eae307"
      },
      {
        "url": "/models/pose/9a9bc17c13ff0a1e/3.bin",
        "byteLength": 25165824,
        "sha256": "836f7b3d183e795281f68ffe857635f8f01efc2356dbfa69953446fcc682cef8"
      },
      {
        "url": "/models/pose/9a9bc17c13ff0a1e/4.bin",
        "byteLength": 25165824,
        "sha256": "61776f1a1fa3a866e13d472eb1f6628362b3516f51ff13f87d0cfaa6a23acb17"
      },
      {
        "url": "/models/pose/9a9bc17c13ff0a1e/5.bin",
        "byteLength": 25165824,
        "sha256": "5ddb24a4269861d99560c9e30d3d842243de5deb0eb930e479af0a5dca25fbfb"
      },
      {
        "url": "/models/pose/9a9bc17c13ff0a1e/6.bin",
        "byteLength": 25165824,
        "sha256": "6d7834d3c3b89eab348bef37f25a890f1f88924bb7aebce6fd8ba1a8d65474a2"
      },
      {
        "url": "/models/pose/9a9bc17c13ff0a1e/7.bin",
        "byteLength": 25165824,
        "sha256": "732a0195b887839b82e4a8c28920c45df40fd832fe958c97cfeb69c323ade799"
      },
      {
        "url": "/models/pose/9a9bc17c13ff0a1e/8.bin",
        "byteLength": 25165824,
        "sha256": "1603e4e4b72083fc94c70c6291016ac23b2663bea128ad3a1a1fe79ef6dfd720"
      },
      {
        "url": "/models/pose/9a9bc17c13ff0a1e/9.bin",
        "byteLength": 2216162,
        "sha256": "14b94d1555ad91bd557a6a809100a518cc08dd271c1482c8225c7b3df805fda8"
      }
    ]
  }
];
export const POSE_MODEL_TOTAL_BYTES = POSE_MODELS.reduce((sum, model) => sum + model.totalByteLength, 0);
